# ASP.NET Core 
# Build and Test ASP.NET Core projects targetting .NET Core 
# Add Steps that run tests, create a NuGet package , deploy and more:

trigger:
- main

pool:
  vmImage: ubuntu-latest 

variables:
  buildConfiguration: 'Release'

steps:
- scripts: donet build -configuration $(buildConfiguration)
  displayName: 'donet build $(buildConfiguration)'


